name: Deploy to cPanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

    - name: Deploy to cPanel
      env:
        SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.CPANEL_SSH_HOST }}
        SSH_USER: ${{ secrets.CPANEL_SSH_USER }}
        REMOTE_PATH: ${{ secrets.CPANEL_REMOTE_PATH }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_github
        chmod 600 ~/.ssh/id_github
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        
        # Test SSH connection
        if ! ssh -i ~/.ssh/id_github -o BatchMode=yes -o StrictHostKeyChecking=accept-new $SSH_USER@$SSH_HOST 'exit'; then
          echo "SSH connection failed"
          exit 1
        fi
        
        # Deploy files
        rsync -avz --delete \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='node_modules/' \
          --exclude='.env' \
          ./ $SSH_USER@$SSH_HOST:$REMOTE_PATH

        if [ $? -eq 0 ]; then
          echo "Deployment successful!"
        else
          echo "Deployment failed"
          exit 1
        fi
